RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "CI/CD for Serverless Applications (Java)"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[site]
BaseURL="/index.html"

[params]
  editURL = "https://github.com/dixonaws/aws-serverless-cicd-workshop/tree/master/workshop/content/"
  description = "Building a CI/CD pipeline for Serverless applications (Java)"
  author = "Fernando Dingler <fdingler@amazon.com>, John Dixon <dixonaws@amazon.com>"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[Languages]
[Languages.en]
title = ""
weight = 1
languageName = "English"